language: swift # or objective-c
osx_image: xcode7.3
xcode_project: Todo.xcodeproj
xcode_scheme: Todo

cache: bundler

rvm:
  - 2.2.5

before_script: 'bundle install'

script:
  - ./test.sh
  - bundle exec cucumber
