language: objective-c
osx_image: xcode7.3

cache:
  - bundler
  - carthage

before_script:
  - carthage build --platform iOS

script:
  - open -b com.apple.iphonesimulator
  - ./unit_test && XCODEPROJ="Todo.xcodeproj" bundle exec cucumber
