#! /bin/bash

set -ex

SYSTEM_KEYCHAIN_PATH="/Library/Keychains/System.keychain"
XCODE_KEYCHAIN_PATH="/Library/Keychains/xcode.keychain"
PROJ_DIR=$(pwd)

if [ ! -f $XCODE_KEYCHAIN_PATH ]; then
  security create-keychain -p $KEYCHAIN_PASSWORD $XCODE_KEYCHAIN_PATH
fi

security unlock-keychain -p $KEYCHAIN_PASSWORD $XCODE_KEYCHAIN_PATH

security import $PROJ_DIR/../cert/todo.p12 -t agg -k $XCODE_KEYCHAIN_PATH -P $CERT_PASSWORD -T /usr/bin/codesign

security default-keychain -s $XCODE_KEYCHAIN_PATH

security list-keychain -s $SYSTEM_KEYCHAIN_PATH $XCODE_KEYCHAIN_PATH
security show-keychain-info $XCODE_KEYCHAIN_PATH

IDENTITIES=$(security find-identity -p codesigning)

if [[ $IDENTITIES == *"0 valid identities found"* ]]
then
  RED='\033[0;31m'
  echo -e "${RED}No identity found."
  exit 1
fi
