#! /bin/bash

set -ex

DEVICE_TARGET=${DEVICE_TARGET:-''}

cd `pwd`

bundle
BUNDLE_ID="io.pivotal.Todo" \
  DEVICE_ENDPOINT="http://$DEVICE_NAME.local:37265" \
  DEVICE_TARGET="$DEVICE_TARGET" \
  bundle exec cucumber
