#! /bin/bash

set -ex

CODE_SIGN_IDENTITY=${CODE_SIGN_IDENTITY:-''}
DEVICE_TARGET=${DEVICE_TARGET:-''}

cd `pwd`

bundle
BUNDLE_ID="io.pivotal.Todo" \
  CODE_SIGN_IDENTITY="$CODE_SIGN_IDENTITY" \
  DEVICE_ENDPOINT="http://$DEVICE_NAME.local:37265" \
  DEVICE_TARGET="$DEVICE_TARGET" \
  bundle exec cucumber
