#! /bin/bash

set -ex

CURR_DIR=$(pwd)
SCHEME="Todo"
PROJECT="$CURR_DIR/Todo.xcodeproj"
TEST_SDK=${SDK:="iphoneos9.3"}
DESTINATION=${DEVICE_STRING:="platform=iOS,name=milo"}

export PATH=/usr/local/bin:$PATH

eval "$(rbenv init -)"

cd $CURR_DIR

whoami
security list-keychain
security find-identity -p codesigning

bundle

xcodebuild \
  -scheme $SCHEME \
  -project $PROJECT \
  -destination "$DESTINATION" \
  -sdk "$TEST_SDK" \
  clean build test \
  # | xcpretty && exit ${PIPESTATUS[0]}
