#! /bin/bash

set -ex

CURR_DIR=$(pwd)
SCHEME="Todo"
PROJECT="$CURR_DIR/Todo.xcodeproj"
TEST_SDK=${SDK:="iphoneos"}
DESTINATION=${DEVICE_STRING:="platform=iOS,name=milo"}

cd $CURR_DIR

bundle

xcodebuild \
  -scheme $SCHEME \
  -project $PROJECT \
  -destination "$DESTINATION" \
  -sdk "$TEST_SDK" \
  PROVISIONING_PROFILE="$PROVISIONING_PROFILE" \
  PROVISIONING_PROFILE_SPECIFIER="$PROVISIONING_PROFILE_SPECIFIER" \
  clean build test \
  | xcpretty && exit ${PIPESTATUS[0]}
