#! /bin/bash

set -ex

CURR_DIR=$(pwd)
SCHEME="Todo"
PROJECT="$CURR_DIR/Todo.xcodeproj"
TEST_SDK=${SDK:="iphoneos9.3"}
DESTINATION=${DEVICE_STRING:="platform=iOS,name=iPhone 1"}

cd $CURR_DIR

bundle

xcodebuild \
  -scheme $SCHEME \
  -project $PROJECT \
  -destination "$DESTINATION" \
  -sdk "$TEST_SDK" \
  clean build test \
  | xcpretty && exit ${PIPESTATUS[0]}
