#! /bin/bash

set -ex

KEYCHAIN_PATH="/Library/Keychains/xcode.keychain"
PROJ_DIR=$(pwd)

echo "Previous keychain: `security default-keychain`"

security unlock-keychain -p $KEYCHAIN_PASSWORD $KEYCHAIN_PATH

security import $PROJ_DIR/../cert/todo.p12 -t agg -k $KEYCHAIN_PATH -P $CERT_PASSWORD -T /usr/bin/codesign

security default-keychain -d system -s $KEYCHAIN_PATH

security find-identity -p codesigning

echo "Current keychain: `security default-keychain`"

whoami
security list-keychain
security show-keychain-info $KEYCHAIN_PATH
security find-identity -p codesigning
