resources:
- name: todo-ios
  type: git
  source:
    uri: https://github.com/alanyjw/Todo.git
    branch: master

jobs:
- name: tests
  plan:
  - get: todo-ios
    trigger: true
  - task: start device
    tags: [ios]
    config:
      platform: darwin
      inputs:
      - name: todo-ios
      run:
        dir: todo-ios
        path: ./run_as
        args:
        - nctx
        - ci/tasks/start_device
  - task: unit test
    tags: [ios]
    config:
      platform: darwin
      inputs:
      - name: todo-ios
      run:
        dir: todo-ios
        path: ./run_as
        args:
        - nctx
        - ci/tasks/unit_test
  - task: automation test
    tags: [ios]
    config:
      platform: darwin
      inputs:
      - name: todo-ios
      run:
        dir: todo-ios
        path: ./run_as
        args:
        - nctx
        - ci/tasks/automation_test
  - task: shutdown device
    tags: [ios]
    config:
      platform: darwin
      inputs:
      - name: todo-ios
      run:
        dir: todo-ios
        path: ./run_as
        args:
        - nctx
        - ci/tasks/shutdown_device
