resources:
- name: todo-ios
  type: git
  source:
    uri: https://github.com/alanyjw/Todo.git
    branch: master
- name: cert
  type: s3
  source:
    bucket: concourseci-xcode
    access_key_id: {{s3-access-key-id}}
    secret_access_key: {{s3-secret-access-key}}
    region_name: ap-southeast-1
    versioned_file: todo/todo.p12

jobs:
- name: tests
  plan:
  - get: todo-ios
    trigger: true
  - get: cert
  - task: add keychain
    tags: [ios]
    params:
      KEYCHAIN_PASSWORD: {{keychain-password}}
      CERT_PASSWORD: {{cert-password}}
    config:
      platform: darwin
      inputs:
      - name: todo-ios
      - name: cert
      run:
        dir: todo-ios
        path: ./ci/tasks/add_keychain
  - task: check device connected
    tags: [ios]
    params:
      DEVICE_NAME: milo
    config:
      platform: darwin
      inputs:
      - name: todo-ios
      run:
        dir: todo-ios
        path: ./run_as
        args:
        - nctx
        - ci/tasks/check_device_connected
  - task: unit test
    tags: [ios]
    config:
      platform: darwin
      inputs:
      - name: todo-ios
      run:
        dir: todo-ios
        path: ./run_as
        args:
        - nctx
        - ci/tasks/unit_test
  - task: automation test
    tags: [ios]
    config:
      platform: darwin
      inputs:
      - name: todo-ios
      params:
        CODE_SIGN_IDENTITY: iPhone Developer: New Context (6K44KRYD64)
        DEVICE_TARGET: eec4222e1b03d82a692d11b56ea965c18df624aa
        DEVICE_NAME: milo
      run:
        dir: todo-ios
        path: ./run_as
        args:
        - nctx
        - ci/tasks/automation_test
  - task: remove keychain
    tags: [ios]
    params:
      KEYCHAIN_PASSWORD: {{keychain-password}}
      CERT_PASSWORD: {{cert-password}}
    config:
      platform: darwin
      inputs:
      - name: todo-ios
      run:
        dir: todo-ios
        path: ./ci/tasks/remove_keychain
