resources:
- name: todo-ios
  type: git
  source:
    uri: https://github.com/alanyjw/Todo.git
    branch: master

jobs:
- name: tests
  plan:
  - get: todo-ios
    trigger: true
  - task: unit test
    tags: [ios]
    config:
      platform: darwin
      inputs:
      - name: todo-ios
      run:
        dir: todo-ios
        path: ./run_test
        args:
        - unit_test
  - task: automation test
    tags: [ios]
    config:
      platform: darwin
      inputs:
      - name: todo-ios
      run:
        dir: todo-ios
        path: ./run_test
        args:
        - automation_test
